// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ParticipantRepoInterface is an autogenerated mock type for the ParticipantRepoInterface type
type ParticipantRepoInterface struct {
	mock.Mock
}

// AnswerQuestion provides a mock function with given fields: idUser, idQuiz, idAnswer, idQuestion, ctx
func (_m *ParticipantRepoInterface) AnswerQuestion(idUser int, idQuiz int, idAnswer int, idQuestion int, ctx context.Context) error {
	ret := _m.Called(idUser, idQuiz, idAnswer, idQuestion, ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, int, int, int, context.Context) error); ok {
		r0 = rf(idUser, idQuiz, idAnswer, idQuestion, ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
